# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-06 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20191006_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
