# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-06 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20191006_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-pub_date']},
        ),
    ]
