# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-06 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20191006_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
