# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-07 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20191007_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
    ]
